/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/Aprender/aprender`; params?: Router.UnknownInputParams; } | { pathname: `/Login`; params?: Router.UnknownInputParams; } | { pathname: `/Mapa`; params?: Router.UnknownInputParams; } | { pathname: `/Otp`; params?: Router.UnknownInputParams; } | { pathname: `/administrador`; params?: Router.UnknownInputParams; } | { pathname: `/camera`; params?: Router.UnknownInputParams; } | { pathname: `/camera/style`; params?: Router.UnknownInputParams; } | { pathname: `/imagem`; params?: Router.UnknownInputParams; } | { pathname: `/imagem/styles`; params?: Router.UnknownInputParams; } | { pathname: `/navigation/AppNavigator`; params?: Router.UnknownInputParams; } | { pathname: `/registo`; params?: Router.UnknownInputParams; } | { pathname: `/screens/AuthoritiesScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/ClinicUpdateScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/DashboardScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/Authorities` | `/Authorities`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/ClinicUpdate` | `/ClinicUpdate`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/Aprender/aprender`; params?: Router.UnknownOutputParams; } | { pathname: `/Login`; params?: Router.UnknownOutputParams; } | { pathname: `/Mapa`; params?: Router.UnknownOutputParams; } | { pathname: `/Otp`; params?: Router.UnknownOutputParams; } | { pathname: `/administrador`; params?: Router.UnknownOutputParams; } | { pathname: `/camera`; params?: Router.UnknownOutputParams; } | { pathname: `/camera/style`; params?: Router.UnknownOutputParams; } | { pathname: `/imagem`; params?: Router.UnknownOutputParams; } | { pathname: `/imagem/styles`; params?: Router.UnknownOutputParams; } | { pathname: `/navigation/AppNavigator`; params?: Router.UnknownOutputParams; } | { pathname: `/registo`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/AuthoritiesScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/ClinicUpdateScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/DashboardScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/Authorities` | `/Authorities`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/ClinicUpdate` | `/ClinicUpdate`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/Aprender/aprender${`?${string}` | `#${string}` | ''}` | `/Login${`?${string}` | `#${string}` | ''}` | `/Mapa${`?${string}` | `#${string}` | ''}` | `/Otp${`?${string}` | `#${string}` | ''}` | `/administrador${`?${string}` | `#${string}` | ''}` | `/camera${`?${string}` | `#${string}` | ''}` | `/camera/style${`?${string}` | `#${string}` | ''}` | `/imagem${`?${string}` | `#${string}` | ''}` | `/imagem/styles${`?${string}` | `#${string}` | ''}` | `/navigation/AppNavigator${`?${string}` | `#${string}` | ''}` | `/registo${`?${string}` | `#${string}` | ''}` | `/screens/AuthoritiesScreen${`?${string}` | `#${string}` | ''}` | `/screens/ClinicUpdateScreen${`?${string}` | `#${string}` | ''}` | `/screens/DashboardScreen${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/Authorities${`?${string}` | `#${string}` | ''}` | `/Authorities${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/ClinicUpdate${`?${string}` | `#${string}` | ''}` | `/ClinicUpdate${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/Aprender/aprender`; params?: Router.UnknownInputParams; } | { pathname: `/Login`; params?: Router.UnknownInputParams; } | { pathname: `/Mapa`; params?: Router.UnknownInputParams; } | { pathname: `/Otp`; params?: Router.UnknownInputParams; } | { pathname: `/administrador`; params?: Router.UnknownInputParams; } | { pathname: `/camera`; params?: Router.UnknownInputParams; } | { pathname: `/camera/style`; params?: Router.UnknownInputParams; } | { pathname: `/imagem`; params?: Router.UnknownInputParams; } | { pathname: `/imagem/styles`; params?: Router.UnknownInputParams; } | { pathname: `/navigation/AppNavigator`; params?: Router.UnknownInputParams; } | { pathname: `/registo`; params?: Router.UnknownInputParams; } | { pathname: `/screens/AuthoritiesScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/ClinicUpdateScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/DashboardScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/Authorities` | `/Authorities`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/ClinicUpdate` | `/ClinicUpdate`; params?: Router.UnknownInputParams; };
    }
  }
}
